version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nwf
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ps1
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: root
    volumes:
      - cache:/var/lib/redis/data
  api:
    container_name: api
    build:
      context: ./backend
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - "postgres"
      - "redis"
    ports:
      - "8000:8000"
  frontend:
    container_name: frontend
    build:
      context: ./client
    depends_on:
      - api
    ports:
      - "3000:3000"
volumes:
  dbdata:
  cache:
